version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app:latest
    networks:
      - frontend
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    env_file:
      - .env
    networks:
      - frontend
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile.server
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    depends_on:
      - react-app
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
